/* Generated by Yosys 0.51 (git sha1 c4b519022, clang++ 10.0.0-4ubuntu1 -fPIC -O3) */

(* hdlname = "apb_downsizer" *)
(* top =  1  *)
(* src = "../rtl/apb_downsizer.sv:2.1-86.10" *)
module apb_downsizer(PCLK, PRESETn, PSELs, PENABLEs, PWRITEs, PADDRs, PWDATAs, PRDATAs, PREADYs, PSELm, PENABLEm, PWRITEm, PADDRm, PWDATAm, PRDATAm, PREADYm);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  (* src = "../rtl/apb_downsizer.sv:5.40-5.46" *)
  output [7:0] PADDRm;
  wire [7:0] PADDRm;
  (* src = "../rtl/apb_downsizer.sv:3.32-3.38" *)
  input [7:0] PADDRs;
  wire [7:0] PADDRs;
  (* src = "../rtl/apb_downsizer.sv:2.28-2.32" *)
  input PCLK;
  wire PCLK;
  (* src = "../rtl/apb_downsizer.sv:4.21-4.29" *)
  output PENABLEm;
  wire PENABLEm;
  (* src = "../rtl/apb_downsizer.sv:2.47-2.55" *)
  input PENABLEs;
  wire PENABLEs;
  (* src = "../rtl/apb_downsizer.sv:5.86-5.93" *)
  input [15:0] PRDATAm;
  wire [15:0] PRDATAm;
  (* src = "../rtl/apb_downsizer.sv:3.77-3.84" *)
  output [31:0] PRDATAs;
  wire [31:0] PRDATAs;
  (* src = "../rtl/apb_downsizer.sv:5.100-5.107" *)
  input PREADYm;
  wire PREADYm;
  (* src = "../rtl/apb_downsizer.sv:3.98-3.105" *)
  output PREADYs;
  wire PREADYs;
  (* src = "../rtl/apb_downsizer.sv:2.33-2.40" *)
  input PRESETn;
  wire PRESETn;
  (* onehot = 32'd1 *)
  wire [4:0] PS;
  (* src = "../rtl/apb_downsizer.sv:4.15-4.20" *)
  output PSELm;
  wire PSELm;
  (* src = "../rtl/apb_downsizer.sv:2.41-2.46" *)
  input PSELs;
  wire PSELs;
  (* src = "../rtl/apb_downsizer.sv:5.66-5.73" *)
  output [15:0] PWDATAm;
  wire [15:0] PWDATAm;
  (* src = "../rtl/apb_downsizer.sv:3.50-3.57" *)
  input [31:0] PWDATAs;
  wire [31:0] PWDATAs;
  (* src = "../rtl/apb_downsizer.sv:4.30-4.37" *)
  output PWRITEm;
  wire PWRITEm;
  (* src = "../rtl/apb_downsizer.sv:2.56-2.63" *)
  input PWRITEs;
  wire PWRITEs;
  (* src = "../rtl/apb_downsizer.sv:13.12-13.18" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] addr_2;
  (* src = "../rtl/apb_downsizer.sv:10.13-10.22" *)
  wire [31:0] read_data;
  NOR2_X1 _197_ (
    .A1(_064_),
    .A2(_076_),
    .ZN(PRDATAs[4])
  );
  NOR2_X1 _198_ (
    .A1(_063_),
    .A2(_076_),
    .ZN(PRDATAs[5])
  );
  NOR2_X1 _199_ (
    .A1(_062_),
    .A2(_076_),
    .ZN(PRDATAs[6])
  );
  NOR2_X1 _200_ (
    .A1(_061_),
    .A2(_076_),
    .ZN(PRDATAs[7])
  );
  NOR2_X1 _201_ (
    .A1(_060_),
    .A2(_076_),
    .ZN(PRDATAs[8])
  );
  NOR2_X1 _202_ (
    .A1(_059_),
    .A2(_076_),
    .ZN(PRDATAs[9])
  );
  NOR2_X1 _203_ (
    .A1(_058_),
    .A2(_076_),
    .ZN(PRDATAs[10])
  );
  NOR2_X1 _204_ (
    .A1(_057_),
    .A2(_076_),
    .ZN(PRDATAs[11])
  );
  NOR2_X1 _205_ (
    .A1(_056_),
    .A2(_076_),
    .ZN(PRDATAs[12])
  );
  NOR2_X1 _206_ (
    .A1(_055_),
    .A2(_076_),
    .ZN(PRDATAs[13])
  );
  NOR2_X1 _207_ (
    .A1(_054_),
    .A2(_076_),
    .ZN(PRDATAs[14])
  );
  NOR2_X1 _208_ (
    .A1(_053_),
    .A2(_076_),
    .ZN(PRDATAs[15])
  );
  NOR2_X1 _209_ (
    .A1(_052_),
    .A2(_076_),
    .ZN(PRDATAs[16])
  );
  NOR2_X1 _210_ (
    .A1(_051_),
    .A2(_076_),
    .ZN(PRDATAs[17])
  );
  NOR2_X1 _211_ (
    .A1(_050_),
    .A2(_076_),
    .ZN(PRDATAs[18])
  );
  NOR2_X1 _212_ (
    .A1(_049_),
    .A2(_076_),
    .ZN(PRDATAs[19])
  );
  NOR2_X1 _213_ (
    .A1(_048_),
    .A2(_076_),
    .ZN(PRDATAs[20])
  );
  NOR2_X1 _214_ (
    .A1(_047_),
    .A2(_076_),
    .ZN(PRDATAs[21])
  );
  NOR2_X1 _215_ (
    .A1(_046_),
    .A2(_076_),
    .ZN(PRDATAs[22])
  );
  NOR2_X1 _216_ (
    .A1(_045_),
    .A2(_076_),
    .ZN(PRDATAs[23])
  );
  NOR2_X1 _217_ (
    .A1(_044_),
    .A2(_076_),
    .ZN(PRDATAs[24])
  );
  NOR2_X1 _218_ (
    .A1(_043_),
    .A2(_076_),
    .ZN(PRDATAs[25])
  );
  NOR2_X1 _219_ (
    .A1(_042_),
    .A2(_076_),
    .ZN(PRDATAs[26])
  );
  NOR2_X1 _220_ (
    .A1(_041_),
    .A2(_076_),
    .ZN(PRDATAs[27])
  );
  NOR2_X1 _221_ (
    .A1(_040_),
    .A2(_076_),
    .ZN(PRDATAs[28])
  );
  NOR2_X1 _222_ (
    .A1(_039_),
    .A2(_076_),
    .ZN(PRDATAs[29])
  );
  NOR2_X1 _223_ (
    .A1(_038_),
    .A2(_076_),
    .ZN(PRDATAs[30])
  );
  NOR2_X1 _224_ (
    .A1(_037_),
    .A2(_076_),
    .ZN(PRDATAs[31])
  );
  AOI21_X1 _225_ (
    .A(PS[2]),
    .B1(PENABLEs),
    .B2(_076_),
    .ZN(_125_)
  );
  AOI21_X1 _226_ (
    .A(_125_),
    .B1(PENABLEs),
    .B2(PS[2]),
    .ZN(PENABLEm)
  );
  NOR2_X1 _227_ (
    .A1(PWRITEs),
    .A2(_097_),
    .ZN(_000_)
  );
  AOI21_X1 _228_ (
    .A(PS[4]),
    .B1(PS[3]),
    .B2(PENABLEs),
    .ZN(_126_)
  );
  OR3_X1 _229_ (
    .A1(_071_),
    .A2(PWRITEs),
    .A3(_126_),
    .ZN(_127_)
  );
  OAI21_X1 _230_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[16]),
    .ZN(_128_)
  );
  AOI21_X1 _231_ (
    .A(_128_),
    .B1(_127_),
    .B2(_068_),
    .ZN(_005_)
  );
  OAI21_X1 _232_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[17]),
    .ZN(_129_)
  );
  AOI21_X1 _233_ (
    .A(_129_),
    .B1(_127_),
    .B2(_067_),
    .ZN(_006_)
  );
  OAI21_X1 _234_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[18]),
    .ZN(_130_)
  );
  AOI21_X1 _235_ (
    .A(_130_),
    .B1(_127_),
    .B2(_066_),
    .ZN(_007_)
  );
  OAI21_X1 _236_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[19]),
    .ZN(_131_)
  );
  AOI21_X1 _237_ (
    .A(_131_),
    .B1(_127_),
    .B2(_065_),
    .ZN(_008_)
  );
  OAI21_X1 _238_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[20]),
    .ZN(_132_)
  );
  AOI21_X1 _239_ (
    .A(_132_),
    .B1(_127_),
    .B2(_064_),
    .ZN(_009_)
  );
  OAI21_X1 _240_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[21]),
    .ZN(_133_)
  );
  AOI21_X1 _241_ (
    .A(_133_),
    .B1(_127_),
    .B2(_063_),
    .ZN(_010_)
  );
  OAI21_X1 _242_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[22]),
    .ZN(_134_)
  );
  AOI21_X1 _243_ (
    .A(_134_),
    .B1(_127_),
    .B2(_062_),
    .ZN(_011_)
  );
  OAI21_X1 _244_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[23]),
    .ZN(_135_)
  );
  AOI21_X1 _245_ (
    .A(_135_),
    .B1(_127_),
    .B2(_061_),
    .ZN(_012_)
  );
  OAI21_X1 _246_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[24]),
    .ZN(_136_)
  );
  AOI21_X1 _247_ (
    .A(_136_),
    .B1(_127_),
    .B2(_060_),
    .ZN(_013_)
  );
  OAI21_X1 _248_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[25]),
    .ZN(_137_)
  );
  AOI21_X1 _249_ (
    .A(_137_),
    .B1(_127_),
    .B2(_059_),
    .ZN(_014_)
  );
  OAI21_X1 _250_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[26]),
    .ZN(_138_)
  );
  AOI21_X1 _251_ (
    .A(_138_),
    .B1(_127_),
    .B2(_058_),
    .ZN(_015_)
  );
  OAI21_X1 _252_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[27]),
    .ZN(_139_)
  );
  AOI21_X1 _253_ (
    .A(_139_),
    .B1(_127_),
    .B2(_057_),
    .ZN(_016_)
  );
  OAI21_X1 _254_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[28]),
    .ZN(_140_)
  );
  AOI21_X1 _255_ (
    .A(_140_),
    .B1(_127_),
    .B2(_056_),
    .ZN(_017_)
  );
  OAI21_X1 _256_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[29]),
    .ZN(_141_)
  );
  AOI21_X1 _257_ (
    .A(_141_),
    .B1(_127_),
    .B2(_055_),
    .ZN(_018_)
  );
  OAI21_X1 _258_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[30]),
    .ZN(_142_)
  );
  AOI21_X1 _259_ (
    .A(_142_),
    .B1(_127_),
    .B2(_054_),
    .ZN(_019_)
  );
  OAI21_X1 _260_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(read_data[31]),
    .ZN(_143_)
  );
  AOI21_X1 _261_ (
    .A(_143_),
    .B1(_127_),
    .B2(_053_),
    .ZN(_020_)
  );
  OAI21_X1 _262_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[0]),
    .ZN(_144_)
  );
  AOI21_X1 _263_ (
    .A(_144_),
    .B1(_127_),
    .B2(_052_),
    .ZN(_021_)
  );
  OAI21_X1 _264_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[1]),
    .ZN(_145_)
  );
  AOI21_X1 _265_ (
    .A(_145_),
    .B1(_127_),
    .B2(_051_),
    .ZN(_022_)
  );
  OAI21_X1 _266_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[2]),
    .ZN(_146_)
  );
  AOI21_X1 _267_ (
    .A(_146_),
    .B1(_127_),
    .B2(_050_),
    .ZN(_023_)
  );
  OAI21_X1 _268_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[3]),
    .ZN(_147_)
  );
  AOI21_X1 _269_ (
    .A(_147_),
    .B1(_127_),
    .B2(_049_),
    .ZN(_024_)
  );
  OAI21_X1 _270_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[4]),
    .ZN(_148_)
  );
  AOI21_X1 _271_ (
    .A(_148_),
    .B1(_127_),
    .B2(_048_),
    .ZN(_025_)
  );
  OAI21_X1 _272_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[5]),
    .ZN(_149_)
  );
  AOI21_X1 _273_ (
    .A(_149_),
    .B1(_127_),
    .B2(_047_),
    .ZN(_026_)
  );
  OAI21_X1 _274_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[6]),
    .ZN(_150_)
  );
  AOI21_X1 _275_ (
    .A(_150_),
    .B1(_127_),
    .B2(_046_),
    .ZN(_027_)
  );
  OAI21_X1 _276_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[7]),
    .ZN(_151_)
  );
  AOI21_X1 _277_ (
    .A(_151_),
    .B1(_127_),
    .B2(_045_),
    .ZN(_028_)
  );
  OAI21_X1 _278_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[8]),
    .ZN(_152_)
  );
  AOI21_X1 _279_ (
    .A(_152_),
    .B1(_127_),
    .B2(_044_),
    .ZN(_029_)
  );
  OAI21_X1 _280_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[9]),
    .ZN(_153_)
  );
  AOI21_X1 _281_ (
    .A(_153_),
    .B1(_127_),
    .B2(_043_),
    .ZN(_030_)
  );
  OAI21_X1 _282_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[10]),
    .ZN(_154_)
  );
  AOI21_X1 _283_ (
    .A(_154_),
    .B1(_127_),
    .B2(_042_),
    .ZN(_031_)
  );
  OAI21_X1 _284_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[11]),
    .ZN(_155_)
  );
  AOI21_X1 _285_ (
    .A(_155_),
    .B1(_127_),
    .B2(_041_),
    .ZN(_032_)
  );
  OAI21_X1 _286_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[12]),
    .ZN(_156_)
  );
  AOI21_X1 _287_ (
    .A(_156_),
    .B1(_127_),
    .B2(_040_),
    .ZN(_033_)
  );
  OAI21_X1 _288_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[13]),
    .ZN(_157_)
  );
  AOI21_X1 _289_ (
    .A(_157_),
    .B1(_127_),
    .B2(_039_),
    .ZN(_034_)
  );
  OAI21_X1 _290_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[14]),
    .ZN(_158_)
  );
  AOI21_X1 _291_ (
    .A(_158_),
    .B1(_127_),
    .B2(_038_),
    .ZN(_035_)
  );
  OAI21_X1 _292_ (
    .A(PRESETn),
    .B1(_127_),
    .B2(PRDATAm[15]),
    .ZN(_159_)
  );
  AOI21_X1 _293_ (
    .A(_159_),
    .B1(_127_),
    .B2(_037_),
    .ZN(_036_)
  );
  INV_X1 _294_ (
    .A(read_data[31]),
    .ZN(_037_)
  );
  INV_X1 _295_ (
    .A(read_data[30]),
    .ZN(_038_)
  );
  INV_X1 _296_ (
    .A(read_data[29]),
    .ZN(_039_)
  );
  INV_X1 _297_ (
    .A(read_data[28]),
    .ZN(_040_)
  );
  INV_X1 _298_ (
    .A(read_data[27]),
    .ZN(_041_)
  );
  INV_X1 _299_ (
    .A(read_data[26]),
    .ZN(_042_)
  );
  INV_X1 _300_ (
    .A(read_data[25]),
    .ZN(_043_)
  );
  INV_X1 _301_ (
    .A(read_data[24]),
    .ZN(_044_)
  );
  INV_X1 _302_ (
    .A(read_data[23]),
    .ZN(_045_)
  );
  INV_X1 _303_ (
    .A(read_data[22]),
    .ZN(_046_)
  );
  INV_X1 _304_ (
    .A(read_data[21]),
    .ZN(_047_)
  );
  INV_X1 _305_ (
    .A(read_data[20]),
    .ZN(_048_)
  );
  INV_X1 _306_ (
    .A(read_data[19]),
    .ZN(_049_)
  );
  INV_X1 _307_ (
    .A(read_data[18]),
    .ZN(_050_)
  );
  INV_X1 _308_ (
    .A(read_data[17]),
    .ZN(_051_)
  );
  INV_X1 _309_ (
    .A(read_data[16]),
    .ZN(_052_)
  );
  INV_X1 _310_ (
    .A(read_data[15]),
    .ZN(_053_)
  );
  INV_X1 _311_ (
    .A(read_data[14]),
    .ZN(_054_)
  );
  INV_X1 _312_ (
    .A(read_data[13]),
    .ZN(_055_)
  );
  INV_X1 _313_ (
    .A(read_data[12]),
    .ZN(_056_)
  );
  INV_X1 _314_ (
    .A(read_data[11]),
    .ZN(_057_)
  );
  INV_X1 _315_ (
    .A(read_data[10]),
    .ZN(_058_)
  );
  INV_X1 _316_ (
    .A(read_data[9]),
    .ZN(_059_)
  );
  INV_X1 _317_ (
    .A(read_data[8]),
    .ZN(_060_)
  );
  INV_X1 _318_ (
    .A(read_data[7]),
    .ZN(_061_)
  );
  INV_X1 _319_ (
    .A(read_data[6]),
    .ZN(_062_)
  );
  INV_X1 _320_ (
    .A(read_data[5]),
    .ZN(_063_)
  );
  INV_X1 _321_ (
    .A(read_data[4]),
    .ZN(_064_)
  );
  INV_X1 _322_ (
    .A(read_data[3]),
    .ZN(_065_)
  );
  INV_X1 _323_ (
    .A(read_data[2]),
    .ZN(_066_)
  );
  INV_X1 _324_ (
    .A(read_data[1]),
    .ZN(_067_)
  );
  INV_X1 _325_ (
    .A(read_data[0]),
    .ZN(_068_)
  );
  INV_X1 _326_ (
    .A(PRESETn),
    .ZN(_069_)
  );
  INV_X1 _327_ (
    .A(PENABLEs),
    .ZN(_070_)
  );
  INV_X1 _328_ (
    .A(PREADYm),
    .ZN(_071_)
  );
  INV_X1 _329_ (
    .A(PS[3]),
    .ZN(_072_)
  );
  INV_X1 _330_ (
    .A(PS[4]),
    .ZN(_073_)
  );
  INV_X1 _331_ (
    .A(PSELs),
    .ZN(_074_)
  );
  INV_X1 _332_ (
    .A(PWRITEs),
    .ZN(_075_)
  );
  INV_X1 _333_ (
    .A(PS[1]),
    .ZN(_076_)
  );
  INV_X1 _334_ (
    .A(PADDRs[3]),
    .ZN(_077_)
  );
  INV_X1 _335_ (
    .A(PWDATAs[16]),
    .ZN(_078_)
  );
  INV_X1 _336_ (
    .A(PWDATAs[17]),
    .ZN(_079_)
  );
  INV_X1 _337_ (
    .A(PWDATAs[18]),
    .ZN(_080_)
  );
  INV_X1 _338_ (
    .A(PWDATAs[19]),
    .ZN(_081_)
  );
  INV_X1 _339_ (
    .A(PWDATAs[20]),
    .ZN(_082_)
  );
  INV_X1 _340_ (
    .A(PWDATAs[21]),
    .ZN(_083_)
  );
  INV_X1 _341_ (
    .A(PWDATAs[22]),
    .ZN(_084_)
  );
  INV_X1 _342_ (
    .A(PWDATAs[23]),
    .ZN(_085_)
  );
  INV_X1 _343_ (
    .A(PWDATAs[24]),
    .ZN(_086_)
  );
  INV_X1 _344_ (
    .A(PWDATAs[25]),
    .ZN(_087_)
  );
  INV_X1 _345_ (
    .A(PWDATAs[26]),
    .ZN(_088_)
  );
  INV_X1 _346_ (
    .A(PWDATAs[27]),
    .ZN(_089_)
  );
  INV_X1 _347_ (
    .A(PWDATAs[28]),
    .ZN(_090_)
  );
  INV_X1 _348_ (
    .A(PWDATAs[29]),
    .ZN(_091_)
  );
  INV_X1 _349_ (
    .A(PWDATAs[30]),
    .ZN(_092_)
  );
  INV_X1 _350_ (
    .A(PWDATAs[31]),
    .ZN(_093_)
  );
  NAND4_X1 _351_ (
    .A1(PRESETn),
    .A2(PENABLEs),
    .A3(PREADYm),
    .A4(PS[3]),
    .ZN(_094_)
  );
  NAND2_X1 _352_ (
    .A1(PS[2]),
    .A2(PRESETn),
    .ZN(_095_)
  );
  OAI21_X1 _353_ (
    .A(_094_),
    .B1(_095_),
    .B2(PREADYm),
    .ZN(_002_)
  );
  OAI21_X1 _354_ (
    .A(PRESETn),
    .B1(_070_),
    .B2(_071_),
    .ZN(_096_)
  );
  OAI22_X1 _355_ (
    .A1(_071_),
    .A2(_095_),
    .B1(_096_),
    .B2(_073_),
    .ZN(_004_)
  );
  NAND4_X1 _356_ (
    .A1(PRESETn),
    .A2(PENABLEs),
    .A3(PREADYm),
    .A4(PS[4]),
    .ZN(_097_)
  );
  AOI211_X1 _357_ (
    .A(_069_),
    .B(PS[1]),
    .C1(PS[0]),
    .C2(_074_),
    .ZN(_098_)
  );
  OAI21_X1 _358_ (
    .A(_098_),
    .B1(_097_),
    .B2(_075_),
    .ZN(_001_)
  );
  NAND3_X1 _359_ (
    .A1(PRESETn),
    .A2(PSELs),
    .A3(PS[0]),
    .ZN(_099_)
  );
  OAI21_X1 _360_ (
    .A(_099_),
    .B1(_096_),
    .B2(_072_),
    .ZN(_003_)
  );
  OR3_X1 _361_ (
    .A1(PS[2]),
    .A2(PS[4]),
    .A3(PS[1]),
    .ZN(_100_)
  );
  NAND2_X1 _362_ (
    .A1(PADDRs[1]),
    .A2(_100_),
    .ZN(_101_)
  );
  XOR2_X1 _363_ (
    .A(PADDRs[1]),
    .B(_100_),
    .Z(PADDRm[1])
  );
  NAND3_X1 _364_ (
    .A1(PADDRs[1]),
    .A2(PADDRs[2]),
    .A3(_100_),
    .ZN(_102_)
  );
  XNOR2_X1 _365_ (
    .A(PADDRs[2]),
    .B(_101_),
    .ZN(PADDRm[2])
  );
  AND4_X1 _366_ (
    .A1(PADDRs[1]),
    .A2(PADDRs[2]),
    .A3(PADDRs[3]),
    .A4(_100_),
    .ZN(_103_)
  );
  AOI21_X1 _367_ (
    .A(_103_),
    .B1(_102_),
    .B2(_077_),
    .ZN(PADDRm[3])
  );
  NAND2_X1 _368_ (
    .A1(PADDRs[4]),
    .A2(_103_),
    .ZN(_104_)
  );
  XOR2_X1 _369_ (
    .A(PADDRs[4]),
    .B(_103_),
    .Z(PADDRm[4])
  );
  NAND3_X1 _370_ (
    .A1(PADDRs[4]),
    .A2(PADDRs[5]),
    .A3(_103_),
    .ZN(_105_)
  );
  XNOR2_X1 _371_ (
    .A(PADDRs[5]),
    .B(_104_),
    .ZN(PADDRm[5])
  );
  NAND4_X1 _372_ (
    .A1(PADDRs[4]),
    .A2(PADDRs[5]),
    .A3(PADDRs[6]),
    .A4(_103_),
    .ZN(_106_)
  );
  XNOR2_X1 _373_ (
    .A(PADDRs[6]),
    .B(_105_),
    .ZN(PADDRm[6])
  );
  XNOR2_X1 _374_ (
    .A(PADDRs[7]),
    .B(_106_),
    .ZN(PADDRm[7])
  );
  OAI21_X1 _375_ (
    .A(PWRITEs),
    .B1(PWDATAs[0]),
    .B2(_100_),
    .ZN(_107_)
  );
  AOI21_X1 _376_ (
    .A(_107_),
    .B1(_100_),
    .B2(_078_),
    .ZN(PWDATAm[0])
  );
  OAI21_X1 _377_ (
    .A(PWRITEs),
    .B1(PWDATAs[1]),
    .B2(_100_),
    .ZN(_108_)
  );
  AOI21_X1 _378_ (
    .A(_108_),
    .B1(_100_),
    .B2(_079_),
    .ZN(PWDATAm[1])
  );
  OAI21_X1 _379_ (
    .A(PWRITEs),
    .B1(PWDATAs[2]),
    .B2(_100_),
    .ZN(_109_)
  );
  AOI21_X1 _380_ (
    .A(_109_),
    .B1(_100_),
    .B2(_080_),
    .ZN(PWDATAm[2])
  );
  OAI21_X1 _381_ (
    .A(PWRITEs),
    .B1(PWDATAs[3]),
    .B2(_100_),
    .ZN(_110_)
  );
  AOI21_X1 _382_ (
    .A(_110_),
    .B1(_100_),
    .B2(_081_),
    .ZN(PWDATAm[3])
  );
  OAI21_X1 _383_ (
    .A(PWRITEs),
    .B1(PWDATAs[4]),
    .B2(_100_),
    .ZN(_111_)
  );
  AOI21_X1 _384_ (
    .A(_111_),
    .B1(_100_),
    .B2(_082_),
    .ZN(PWDATAm[4])
  );
  OAI21_X1 _385_ (
    .A(PWRITEs),
    .B1(PWDATAs[5]),
    .B2(_100_),
    .ZN(_112_)
  );
  AOI21_X1 _386_ (
    .A(_112_),
    .B1(_100_),
    .B2(_083_),
    .ZN(PWDATAm[5])
  );
  OAI21_X1 _387_ (
    .A(PWRITEs),
    .B1(PWDATAs[6]),
    .B2(_100_),
    .ZN(_113_)
  );
  AOI21_X1 _388_ (
    .A(_113_),
    .B1(_100_),
    .B2(_084_),
    .ZN(PWDATAm[6])
  );
  OAI21_X1 _389_ (
    .A(PWRITEs),
    .B1(PWDATAs[7]),
    .B2(_100_),
    .ZN(_114_)
  );
  AOI21_X1 _390_ (
    .A(_114_),
    .B1(_100_),
    .B2(_085_),
    .ZN(PWDATAm[7])
  );
  OAI21_X1 _391_ (
    .A(PWRITEs),
    .B1(PWDATAs[8]),
    .B2(_100_),
    .ZN(_115_)
  );
  AOI21_X1 _392_ (
    .A(_115_),
    .B1(_100_),
    .B2(_086_),
    .ZN(PWDATAm[8])
  );
  OAI21_X1 _393_ (
    .A(PWRITEs),
    .B1(PWDATAs[9]),
    .B2(_100_),
    .ZN(_116_)
  );
  AOI21_X1 _394_ (
    .A(_116_),
    .B1(_100_),
    .B2(_087_),
    .ZN(PWDATAm[9])
  );
  OAI21_X1 _395_ (
    .A(PWRITEs),
    .B1(PWDATAs[10]),
    .B2(_100_),
    .ZN(_117_)
  );
  AOI21_X1 _396_ (
    .A(_117_),
    .B1(_100_),
    .B2(_088_),
    .ZN(PWDATAm[10])
  );
  OAI21_X1 _397_ (
    .A(PWRITEs),
    .B1(PWDATAs[11]),
    .B2(_100_),
    .ZN(_118_)
  );
  AOI21_X1 _398_ (
    .A(_118_),
    .B1(_100_),
    .B2(_089_),
    .ZN(PWDATAm[11])
  );
  OAI21_X1 _399_ (
    .A(PWRITEs),
    .B1(PWDATAs[12]),
    .B2(_100_),
    .ZN(_119_)
  );
  AOI21_X1 _400_ (
    .A(_119_),
    .B1(_100_),
    .B2(_090_),
    .ZN(PWDATAm[12])
  );
  OAI21_X1 _401_ (
    .A(PWRITEs),
    .B1(PWDATAs[13]),
    .B2(_100_),
    .ZN(_120_)
  );
  AOI21_X1 _402_ (
    .A(_120_),
    .B1(_100_),
    .B2(_091_),
    .ZN(PWDATAm[13])
  );
  OAI21_X1 _403_ (
    .A(PWRITEs),
    .B1(PWDATAs[14]),
    .B2(_100_),
    .ZN(_121_)
  );
  AOI21_X1 _404_ (
    .A(_121_),
    .B1(_100_),
    .B2(_092_),
    .ZN(PWDATAm[14])
  );
  OAI21_X1 _405_ (
    .A(PWRITEs),
    .B1(PWDATAs[15]),
    .B2(_100_),
    .ZN(_122_)
  );
  AOI21_X1 _406_ (
    .A(_122_),
    .B1(_100_),
    .B2(_093_),
    .ZN(PWDATAm[15])
  );
  NAND2_X1 _407_ (
    .A1(PSELs),
    .A2(_076_),
    .ZN(_123_)
  );
  OAI22_X1 _408_ (
    .A1(_074_),
    .A2(PWRITEs),
    .B1(PS[1]),
    .B2(PS[4]),
    .ZN(_124_)
  );
  XNOR2_X1 _409_ (
    .A(_123_),
    .B(_124_),
    .ZN(PREADYs)
  );
  NOR2_X1 _410_ (
    .A1(_068_),
    .A2(_076_),
    .ZN(PRDATAs[0])
  );
  NOR2_X1 _411_ (
    .A1(_067_),
    .A2(_076_),
    .ZN(PRDATAs[1])
  );
  NOR2_X1 _412_ (
    .A1(_066_),
    .A2(_076_),
    .ZN(PRDATAs[2])
  );
  NOR2_X1 _413_ (
    .A1(_065_),
    .A2(_076_),
    .ZN(PRDATAs[3])
  );
  DFF_X1 _414_ (
    .CK(PCLK),
    .D(_001_),
    .Q(PS[0]),
    .QN(_193_)
  );
  DFF_X1 _415_ (
    .CK(PCLK),
    .D(_000_),
    .Q(PS[1]),
    .QN(_194_)
  );
  DFF_X1 _416_ (
    .CK(PCLK),
    .D(_002_),
    .Q(PS[2]),
    .QN(_195_)
  );
  DFF_X1 _417_ (
    .CK(PCLK),
    .D(_003_),
    .Q(PS[3]),
    .QN(_196_)
  );
  DFF_X1 _418_ (
    .CK(PCLK),
    .D(_004_),
    .Q(PS[4]),
    .QN(_192_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _419_ (
    .CK(PCLK),
    .D(_005_),
    .Q(read_data[0]),
    .QN(_191_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _420_ (
    .CK(PCLK),
    .D(_006_),
    .Q(read_data[1]),
    .QN(_190_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _421_ (
    .CK(PCLK),
    .D(_007_),
    .Q(read_data[2]),
    .QN(_189_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _422_ (
    .CK(PCLK),
    .D(_008_),
    .Q(read_data[3]),
    .QN(_188_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _423_ (
    .CK(PCLK),
    .D(_009_),
    .Q(read_data[4]),
    .QN(_187_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _424_ (
    .CK(PCLK),
    .D(_010_),
    .Q(read_data[5]),
    .QN(_186_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _425_ (
    .CK(PCLK),
    .D(_011_),
    .Q(read_data[6]),
    .QN(_185_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _426_ (
    .CK(PCLK),
    .D(_012_),
    .Q(read_data[7]),
    .QN(_184_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _427_ (
    .CK(PCLK),
    .D(_013_),
    .Q(read_data[8]),
    .QN(_183_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _428_ (
    .CK(PCLK),
    .D(_014_),
    .Q(read_data[9]),
    .QN(_182_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _429_ (
    .CK(PCLK),
    .D(_015_),
    .Q(read_data[10]),
    .QN(_181_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _430_ (
    .CK(PCLK),
    .D(_016_),
    .Q(read_data[11]),
    .QN(_180_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _431_ (
    .CK(PCLK),
    .D(_017_),
    .Q(read_data[12]),
    .QN(_179_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _432_ (
    .CK(PCLK),
    .D(_018_),
    .Q(read_data[13]),
    .QN(_178_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _433_ (
    .CK(PCLK),
    .D(_019_),
    .Q(read_data[14]),
    .QN(_177_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _434_ (
    .CK(PCLK),
    .D(_020_),
    .Q(read_data[15]),
    .QN(_176_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _435_ (
    .CK(PCLK),
    .D(_021_),
    .Q(read_data[16]),
    .QN(_175_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _436_ (
    .CK(PCLK),
    .D(_022_),
    .Q(read_data[17]),
    .QN(_174_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _437_ (
    .CK(PCLK),
    .D(_023_),
    .Q(read_data[18]),
    .QN(_173_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _438_ (
    .CK(PCLK),
    .D(_024_),
    .Q(read_data[19]),
    .QN(_172_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _439_ (
    .CK(PCLK),
    .D(_025_),
    .Q(read_data[20]),
    .QN(_171_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _440_ (
    .CK(PCLK),
    .D(_026_),
    .Q(read_data[21]),
    .QN(_170_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _441_ (
    .CK(PCLK),
    .D(_027_),
    .Q(read_data[22]),
    .QN(_169_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _442_ (
    .CK(PCLK),
    .D(_028_),
    .Q(read_data[23]),
    .QN(_168_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _443_ (
    .CK(PCLK),
    .D(_029_),
    .Q(read_data[24]),
    .QN(_167_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _444_ (
    .CK(PCLK),
    .D(_030_),
    .Q(read_data[25]),
    .QN(_166_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _445_ (
    .CK(PCLK),
    .D(_031_),
    .Q(read_data[26]),
    .QN(_165_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _446_ (
    .CK(PCLK),
    .D(_032_),
    .Q(read_data[27]),
    .QN(_164_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _447_ (
    .CK(PCLK),
    .D(_033_),
    .Q(read_data[28]),
    .QN(_163_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _448_ (
    .CK(PCLK),
    .D(_034_),
    .Q(read_data[29]),
    .QN(_162_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _449_ (
    .CK(PCLK),
    .D(_035_),
    .Q(read_data[30]),
    .QN(_161_)
  );
  (* src = "../rtl/apb_downsizer.sv:18.1-27.4" *)
  DFF_X1 _450_ (
    .CK(PCLK),
    .D(_036_),
    .Q(read_data[31]),
    .QN(_160_)
  );
  assign PADDRm[0] = PADDRs[0];
  assign PSELm = PSELs;
  assign PWRITEm = PWRITEs;
  assign addr_2[0] = PADDRs[0];
endmodule
